[package]
name = "anticanonicalize"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/ComputerDruid/anticanonicalize"
license = "MIT OR Apache-2.0"

[dependencies]
rustix = { version = "1.1.3", features = [ "net", "process", "stdio"] }
tempfile = "3.25.0"
